# .streamlit/secrets.toml
SUPABASE_URL = "https://penvfjflwkshgijsejun.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlbnZmamZsd2tzaGdpanNlanVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5OTM0MDIsImV4cCI6MjA3NzU2OTQwMn0.Jv2Hduwzzn020KRjB1WoUUCppCgUt2IjMnfINkioooE" 
SUPABASE_BUCKET = "fetched-data"  # or the bucket name you created
